test:
    path: /test/{age}
    controller: App\Controller\TestController::test
    methods: [GET, POST]
    host: 
    schemes: [https, http]
    defaults: 
        age: 0
    requirements:
        age: \d+